# Calculation Code :

### `Study of Characteristics of CCD Camera`
Exp Date : 21st Feb,23

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#=====|Data File for CCD Experiment|====================================================
#CCD temperature : 16.95â„ƒ,	Focus peak count = 54963,	Time : 150s	
#Pixel Coordinate : x = 400, y = 270
#6	566	596	555	548	559

df = pd.read_excel('Datafile.xlsx')
df

   # Fig No.   Center(O)  Up(U)  Down(D)  Left(L)  Right(R)
0           1        214    198      208      206       193
1           2        202    206      205      209       212
2           3        206    196      192      187       200
3           4        217    195      201      188       203
4           5        233    189      195      211       202

In [3]:
avg_count = []
sd_count = []
conversion_factor = []
q_eff = 0.6
actual_count = []
sum_f = 0

for key in ['Center(O)', 'Up(U)', 'Down(D)', 'Left(L)', 'Right(R)']:
    avg = np.average(df[key])
    sd = np.std(df[key])
    f = avg/sd**2
    f_actual = f/q_eff
    
    sum_f = sum_f + f_actual
    
    avg_count.append(avg)
    sd_count.append(sd)
    conversion_factor.append(f)
    actual_count.append(int(f_actual))

net_f = sum_f/5

calc_df = {'Pixel': ['Center(O)', 'Up(U)', 'Down(D)', 'Left(L)', 'Right(R)'],
           'Pixel Location': [(400,270), (400, 269), (400, 271), (399, 270), (301, 270)],
           'Average Count': avg_count, 'SD' : sd_count, 'Conversion Factor': conversion_factor, 
           'Quantum Efficiency': q_eff * np.ones(5), 'Actual conversion factor(Photon Count/ADU)': actual_count}

calc_df = pd.DataFrame(calc_df)
print('Average conversion factor (Photon counts per ADU) : ', int(net_f))
calc_df

Average conversion factor (Photon counts per ADU) :  7

,Pixel,Pixel Location,Average Count,SD,Conversion Factor,Quantum Efficiency,Actual conversion factor(Photon Count/ADU)
0,Center(O),"(400, 270)",214.4,10.744301,1.857242,0.6,3
1,Up(U),"(400, 269)",196.8,5.491812,6.525199,0.6,10
2,Down(D),"(400, 271)",200.2,5.979967,5.598434,0.6,9
3,Left(L),"(399, 270)",200.2,10.495713,1.817357,0.6,3
4,Right(R),"(301, 270)",202.0,6.099180,5.430108,0.6,9

In [4]:
calc_df.to_excel('Calculated data.xlsx')